### PR TITLE
UI-74 Storybook Component Variant Headings

### PR DESCRIPTION
**Pull request by Sonicrida**
Closes UI-74

Add the storybook chapters addon to display headings for each component variant. 

image

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Do you prefer the story code grouped together for all chapters in "Show Info" or using the chapters plugin sections with one code block each? Also, can we reduce the vertical spacing between headings?

**Comment by Sonicrida** [comment]
Personally I prefer the chapter code blocks. Also I reduced spacing but had to use a `!important` for it in the storybook config. I tried to disable the default chapters theme but that ended up breaking the whole story for some reason.

**Comment by nickmccurdy** [comment]
Yea, I think I prefer that information inline too. I actually had the "Show Info" button disabled originally, but I had to enable it due to a bug in Storybook 4 (fortunately the chapter plugin works around it.

Alternatively, what if we had a separate story for each variant instead of chapters? Here's an example, note the separate variants in the sidebar: https://storybooks-official.netlify.com/?selectedKind=Addons%7Ca11y%2FButton&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by nickmccurdy** [comment]
We decided to have a separate story per variant instead.

**Pull request closed without merging**
