### PR TITLE
Add responsive baseline style for fluid typography

### PR DESCRIPTION
**Pull request by Sonicrida**
UI-38

Adds `fluidRange` from `polished` to the `<Typography />` component to allow font-size to scale up and down based on window size.

image

image

Scales from 16px to 20px between the breakpoints of 400px and 1000px currently but these can be changed as necessary.

### CODE REVIEW

**Comment by Sonicrida** [comment]
This may be a good candidate for a design review as well?

**Comment by nickmccurdy** [comment]
Design review sounds like a good idea, if we can find some time this sprint (a one-off call or Slack chat may be easier than waiting for the next meeting).

I'd like to figure out if we can get this to use em before merging since otherwise we'd partially lose the ability to resize UI based on the browser font size. If fluidRange doesn't support em, maybe we could write a wrapper function that converts between em and pixels while using fluidRange to calculate the sizes in pixels. I believe polished already has functions to convert between em and rem, so we'd just need to use them with fluidrange.

**Comment by nickmccurdy** [comment]
Can you please add some device presets (at least one for mobile and desktop)? This is all I'm seeing and the options don't change the story display.
image

**Comment by Sonicrida** [comment]
Got the viewport selection working and added some options! If this looks good, we can merge but I can also add other options for viewport sizes if you'd like to test different screens. Alternatively we can do that in a separate story.

**Comment by nickmccurdy** [comment]
I noticed that Heading doesn't have the same font size, but it should be larger than 22px on a wider display. Everything else looks good including the viewport config.

**Comment by nickmccurdy** [comment]
Did we get to do a design review on that? Otherwise it seems done.

**Comment by Sonicrida** [comment]
Yeah we did already. As long as the heading sizes look solid, we're good to merge this.

**Pull request merged**
