### PR TITLE
Select Address Support

### PR DESCRIPTION
**Pull request by nickmccurdy**
Blocks https://github.com/MyCryptoHQ/MyCrypto/pull/2495 ([CW-29](https://mycrypto.atlassian.net/browse/CW-29))

https://mycryptobuilds.com/ui/optional-address-title/

- [x]  Make Address title optional
  - This allows Addresses to be used with an identicon but without a title/label, such as when selecting unlabelled addresses in a mnemonic/hardware wallet.
  - [Storybook Story](https://mycryptobuilds.com/ui/optional-address-title/?selectedKind=Molecules&selectedStory=Address&full=0&addons=1&stories=1&panelRight=0&addonPanel=%40storybook%2Faddon-a11y%2Fpanel)
image
- [x] ~Use monospace font for addresses~ Allow external styling of Address so core can use a monospace font
- [x] Address div should have a align-items: center;
- [x] ~Disable~ Fix responsive typography
- [x] Make identicon 2-2.5 times the height of the font size
- [x] Move monospace style from core to Address

### CODE REVIEW

**Comment by nickmccurdy** [comment]
On hold until I'm sure that we need this

**Comment by nickmccurdy** [comment]
We will need this in the updated design, but with a "No Label" placeholder instead of showing nothing for the title. https://app.zeplin.io/project/5b0334f5e91e8c481645ad56/screen/5cb508f9b151eb0c282ee304

**Comment by nickmccurdy** [comment]
Pre-released as `0.15.0-optional-address-title@optional-address-title`

**Comment by nickmccurdy** [comment]
@Sonicrida I'm ready for a review again whenever you have time

**Comment by Sonicrida** [comment]
This looks good to me! Good work

**Pull request merged**
